# Generated by Django 2.2.3 on 2019-07-09 22:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical_professional', '0005_auto_20190709_1714'),
        ('organ', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('street_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(default='United States', max_length=50)),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('domain_url', models.CharField(max_length=200)),
                ('support_email', models.CharField(max_length=100)),
                ('work_phone_number1', models.CharField(max_length=12)),
                ('work_phone_number2', models.CharField(default='', max_length=12)),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserOrganization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization', verbose_name='the related organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationOrgan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organ.Organ', verbose_name='the related organ')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization', verbose_name='the related organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Address', verbose_name='the related address')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization', verbose_name='the related organization')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalProfessionalOrganization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medical_professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_professional.MedicalProfessional', verbose_name='the related medical professional')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization', verbose_name='the related organization')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalProfessionalAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Address', verbose_name='the related address')),
                ('medical_professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_professional.MedicalProfessional', verbose_name='the related medical professional')),
            ],
        ),
    ]
