# Generated by Django 2.2.3 on 2019-07-10 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organ', '0004_personorgan'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Address', verbose_name='the related address')),
                ('organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organ.Organ', verbose_name='the related medical organ')),
            ],
        ),
    ]
