# Generated by Django 2.2.3 on 2019-07-05 23:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_professional', '0002_auto_20190705_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('illness_name', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=10000)),
                ('comment', models.CharField(default='', max_length=10000)),
                ('urgency', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('organ_type', models.CharField(max_length=200)),
                ('description', models.CharField(default='', max_length=10000)),
                ('comment', models.CharField(default='', max_length=10000)),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_exactred', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
                ('is_expired', models.BooleanField(default=False)),
                ('organ_image', models.ImageField(default='organ_default.jpg', upload_to='organ_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('race', models.CharField(default='unknown', max_length=50)),
                ('blood_type', models.CharField(default='unknown', max_length=50)),
                ('weight', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('height', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('is_alive', models.BooleanField(default=True)),
                ('who', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PersonIllness',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('illness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organ.Illness', verbose_name='the related illness')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organ.Person', verbose_name='the related person')),
            ],
        ),
        migrations.CreateModel(
            name='OrganWatched',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medical_professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_professional.MedicalProfessional', verbose_name='the related medial professional')),
                ('organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organ.Organ', verbose_name='the related medical Organ')),
            ],
        ),
        migrations.CreateModel(
            name='OrganRequested',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medical_professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_professional.MedicalProfessional', verbose_name='the related medial professional')),
                ('organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organ.Organ', verbose_name='the related medical Organ')),
            ],
        ),
        migrations.CreateModel(
            name='OrganReleased',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medical_professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_professional.MedicalProfessional', verbose_name='the related medial professional')),
                ('organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organ.Organ', verbose_name='the related medical Organ')),
            ],
        ),
    ]
