# Generated by Django 2.2.3 on 2019-07-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organ', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='comment',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
