# Generated by Django 2.2.3 on 2019-07-09 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organ', '0002_person_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organ',
            old_name='date_exactred',
            new_name='date_extracted',
        ),
    ]
