# Generated by Django 2.2.3 on 2019-07-09 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organ', '0003_auto_20190709_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonOrgan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organ.Organ', verbose_name='the related medical Organ')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organ.Person', verbose_name='the related person')),
            ],
        ),
    ]
