# Generated by Django 2.2.3 on 2019-07-11 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organ', '0004_personorgan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
    ]
