# Generated by Django 2.2.3 on 2019-07-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organ', '0006_remove_organ_date_extracted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organ',
            name='expiration_date',
            field=models.CharField(max_length=200),
        ),
    ]
