# Generated by Django 2.2.3 on 2019-07-05 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('street_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalProfessional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_ID', models.CharField(max_length=100)),
                ('cellphone_number', models.CharField(max_length=12)),
                ('work_phone_number', models.CharField(default='', max_length=12)),
                ('profile_image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('domain_url', models.CharField(max_length=200)),
                ('support_email', models.CharField(max_length=100)),
                ('work_phone_number1', models.CharField(max_length=12)),
                ('work_phone_number2', models.CharField(default='', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position_name', models.CharField(max_length=100)),
                ('role', models.CharField(default='', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_professional.Address', verbose_name='the related Address')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_professional.Organization', verbose_name='the related organization')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalProfessionalPosition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medical_professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_professional.MedicalProfessional', verbose_name='the related medical professional')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_professional.Position', verbose_name='the related position')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalProfessionalOrganization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medical_professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_professional.MedicalProfessional', verbose_name='the related medical professional')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_professional.Organization', verbose_name='the related organization')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalProfessionalAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_professional.Address', verbose_name='the related address')),
                ('medical_professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_professional.MedicalProfessional', verbose_name='the related medical professional')),
            ],
        ),
    ]
