# Generated by Django 2.2.3 on 2019-07-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_professional', '0002_auto_20190705_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprofessional',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
