# Generated by Django 2.2.3 on 2019-07-09 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_professional', '0004_auto_20190707_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalprofessionaladdress',
            name='address',
        ),
        migrations.RemoveField(
            model_name='medicalprofessionaladdress',
            name='medical_professional',
        ),
        migrations.RemoveField(
            model_name='medicalprofessionalorganization',
            name='medical_professional',
        ),
        migrations.RemoveField(
            model_name='medicalprofessionalorganization',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organizationaddress',
            name='address',
        ),
        migrations.RemoveField(
            model_name='organizationaddress',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='MedicalProfessionalAddress',
        ),
        migrations.DeleteModel(
            name='MedicalProfessionalOrganization',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='OrganizationAddress',
        ),
    ]
